# Generated by Django 3.2.25 on 2025-06-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='', upload_to='blog_images/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
